-- Seed data for Indian cities and their areas
-- This file populates all areas in Ghaziabad, Delhi, and Noida

-- Cities
INSERT INTO cities (name, description, latitude, longitude) VALUES
('Ghaziabad', 'Industrial city in Uttar Pradesh', 28.6692, 77.4538),
('Delhi', 'Capital of India', 28.7041, 77.1025),
('Noida', 'Technology and industrial city in Uttar Pradesh', 28.5805, 77.3910)
ON CONFLICT (name) DO NOTHING;

-- GHAZIABAD Areas (Comprehensive)
INSERT INTO areas (city_id, name, description, latitude, longitude) VALUES
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Indirapuram', 'Upscale residential area', 28.5921, 77.3674),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Vaishali', 'Planned residential sector', 28.5855, 77.3552),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Kaushambi', 'Modern township', 28.6011, 77.3703),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Raj Nagar', 'Established residential area', 28.6741, 77.4156),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Raj Nagar Extension', 'Extended residential', 28.6650, 77.4100),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Kavi Nagar', 'Residential locality', 28.6550, 77.4050),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Nehru Nagar', 'Residential area', 28.6450, 77.4000),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Patel Nagar', 'Residential zone', 28.6350, 77.3950),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Vijay Nagar', 'Commercial and residential', 28.6822, 77.4243),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Govindpuram', 'Developing area', 28.5712, 77.4098),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Wave City', 'Modern township', 28.6100, 77.4300),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Crossings Republik', 'Residential township', 28.6312, 77.3889),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Vasundhara', 'Residential area', 28.6200, 77.4200),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Sahibabad', 'Residential locality', 28.6500, 77.4500),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Mohan Nagar', 'Residential area', 28.6634, 77.4127),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Loni', 'Industrial and residential', 28.6821, 77.4321),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Muradnagar', 'Residential area', 28.7000, 77.4600),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Modinagar', 'Industrial area', 28.7200, 77.4700),
((SELECT id FROM cities WHERE name = 'Ghaziabad'), 'Dasna', 'Residential locality', 28.7400, 77.4800)
ON CONFLICT DO NOTHING;

-- DELHI Areas (Comprehensive)
INSERT INTO areas (city_id, name, description, latitude, longitude) VALUES
((SELECT id FROM cities WHERE name = 'Delhi'), 'Rohini', 'Planned residential zone', 28.7948, 77.0506),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Dwarka', 'Modern township', 28.5921, 77.0460),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Janakpuri', 'Residential sector', 28.5189, 77.1180),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Uttam Nagar', 'Residential area', 28.6356, 77.0707),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Vikaspuri', 'Residential locality', 28.5744, 77.0977),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Paschim Vihar', 'Residential zone', 28.5505, 77.0924),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Pitampura', 'North Delhi residential', 28.7469, 77.1119),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Shalimar Bagh', 'Residential area', 28.7542, 77.0897),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Ashok Vihar', 'Residential zone', 28.6472, 77.0826),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Model Town', 'Premium residential', 28.7390, 77.2104),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Civil Lines', 'Historic area', 28.6512, 77.2294),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Karol Bagh', 'Shopping and residential', 28.6452, 77.1894),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Rajouri Garden', 'Residential area', 28.6386, 77.1144),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Punjabi Bagh', 'Residential zone', 28.6514, 77.1195),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Lajpat Nagar', 'Commercial and residential', 28.5656, 77.2300),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Greater Kailash', 'Premium residential', 28.5244, 77.2365),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Defence Colony', 'Upscale residential', 28.5694, 77.2374),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Saket', 'Residential area', 28.5244, 77.1696),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Malviya Nagar', 'Residential zone', 28.5316, 77.1896),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Hauz Khas', 'Student and commercial area', 28.5244, 77.2095),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Green Park', 'Upscale residential', 28.5355, 77.1965),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Vasant Kunj', 'Upscale residential', 28.5194, 77.1762),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Vasant Vihar', 'Premium residential', 28.5226, 77.1827),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Chanakyapuri', 'Diplomatic enclave', 28.5915, 77.2175),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Mayur Vihar', 'Residential township', 28.5850, 77.2620),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Preet Vihar', 'Residential area', 28.5969, 77.2730),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Laxmi Nagar', 'Commercial and residential', 28.5880, 77.2552),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Shahdara', 'Residential zone', 28.6139, 77.2762),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Dilshad Garden', 'Residential area', 28.6097, 77.3070),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Yamuna Vihar', 'Residential locality', 28.5991, 77.2954),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Krishna Nagar', 'Residential area', 28.6417, 77.2706),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Burari', 'North Delhi residential', 28.7606, 77.1488),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Narela', 'Residential zone', 28.8448, 77.1086),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Bawana', 'Residential area', 28.7849, 77.0431),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Alipur', 'Residential locality', 28.8054, 77.1571),
((SELECT id FROM cities WHERE name = 'Delhi'), 'Najafgarh', 'South Delhi area', 28.4699, 77.0409)
ON CONFLICT DO NOTHING;

-- NOIDA Areas (All Sectors - Comprehensive)
INSERT INTO areas (city_id, name, description, latitude, longitude) VALUES
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 1', 'Commercial and residential', 28.6050, 77.3700),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 2', 'Residential sector', 28.6040, 77.3720),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 3', 'Residential area', 28.6030, 77.3740),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 4', 'Residential sector', 28.6020, 77.3760),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 5', 'Residential area', 28.6010, 77.3780),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 6', 'Residential sector', 28.6000, 77.3800),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 7', 'Residential area', 28.5990, 77.3820),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 8', 'Residential sector', 28.5980, 77.3840),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 9', 'Residential area', 28.5970, 77.3860),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 10', 'Residential sector', 28.5960, 77.3880),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 11', 'Residential area', 28.5950, 77.3900),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 12', 'Commercial and residential', 28.5940, 77.3920),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 14', 'Residential sector', 28.5920, 77.3960),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 15', 'Residential area', 28.5910, 77.3980),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 16', 'Residential sector', 28.5900, 77.4000),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 18', 'Commercial hub', 28.5880, 77.4040),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 19', 'Residential area', 28.5870, 77.4060),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 20', 'Residential sector', 28.5860, 77.4080),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 21', 'Residential area', 28.5850, 77.4100),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 22', 'Residential sector', 28.5840, 77.4120),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 23', 'Commercial and residential', 28.5830, 77.4140),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 24', 'Residential area', 28.5820, 77.4160),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 25', 'Residential sector', 28.5810, 77.4180),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 26', 'Residential area', 28.5800, 77.4200),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 27', 'Residential sector', 28.5790, 77.4220),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 28', 'Residential area', 28.5780, 77.4240),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 29', 'Residential sector', 28.5770, 77.4260),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 30', 'Residential area', 28.5760, 77.4280),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 31', 'Residential sector', 28.5750, 77.4300),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 32', 'Residential area', 28.5740, 77.4320),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 33', 'Residential sector', 28.5730, 77.4340),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 34', 'Residential area', 28.5720, 77.4360),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 35', 'Residential sector', 28.5710, 77.4380),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 36', 'Residential area', 28.5700, 77.4400),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 37', 'Residential sector', 28.5690, 77.4420),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 39', 'IT and business park', 28.5670, 77.4460),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 41', 'Business district', 28.5650, 77.4500),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 44', 'Commercial and residential', 28.5620, 77.4560),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 45', 'Residential area', 28.5610, 77.4580),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 46', 'Residential sector', 28.5600, 77.4600),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 47', 'Residential area', 28.5590, 77.4620),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 48', 'Residential sector', 28.5580, 77.4640),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 49', 'Residential area', 28.5570, 77.4660),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 50', 'Residential sector', 28.5560, 77.4680),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 51', 'Residential area', 28.5550, 77.4700),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 52', 'Residential sector', 28.5540, 77.4720),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 55', 'Residential area', 28.5510, 77.4780),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 56', 'Residential sector', 28.5500, 77.4800),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 57', 'Residential area', 28.5490, 77.4820),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 61', 'Business district', 28.5450, 77.4900),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 62', 'IT hub', 28.5440, 77.4920),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 63', 'Commercial district', 28.5430, 77.4940),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 70', 'Residential area', 28.5360, 77.5060),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 71', 'Residential sector', 28.5350, 77.5080),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 72', 'Residential area', 28.5340, 77.5100),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 73', 'Residential sector', 28.5330, 77.5120),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 74', 'Residential area', 28.5320, 77.5140),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 75', 'Residential sector', 28.5310, 77.5160),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 76', 'Residential area', 28.5300, 77.5180),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 77', 'Residential sector', 28.5290, 77.5200),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 78', 'Residential area', 28.5280, 77.5220),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 79', 'Residential sector', 28.5270, 77.5240),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 93', 'Residential area', 28.5150, 77.5420),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 104', 'Residential sector', 28.5000, 77.5680),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 105', 'Residential area', 28.4990, 77.5700),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 107', 'Residential sector', 28.4970, 77.5740),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 108', 'Residential area', 28.4960, 77.5760),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 110', 'Residential sector', 28.4940, 77.5800),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 135', 'Residential area', 28.4750, 77.6160),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 137', 'New development', 28.4730, 77.6200),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 143', 'Residential sector', 28.4680, 77.6300),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 144', 'Residential area', 28.4670, 77.6320),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 150', 'Residential sector', 28.4600, 77.6460),
((SELECT id FROM cities WHERE name = 'Noida'), 'Sector 168', 'Residential area', 28.4450, 77.6760)
ON CONFLICT DO NOTHING;

-- Add neighborhoods for Ghaziabad areas
INSERT INTO neighborhoods (area_id, name, postal_code, description) VALUES
-- Indirapuram neighborhoods (Khand-based)
((SELECT id FROM areas WHERE name = 'Indirapuram' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Ahinsa Khand 1', '201014', 'Ahinsa Khand zone 1'),
((SELECT id FROM areas WHERE name = 'Indirapuram' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Ahinsa Khand 2', '201014', 'Ahinsa Khand zone 2'),
((SELECT id FROM areas WHERE name = 'Indirapuram' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Niti Khand 1', '201014', 'Niti Khand zone 1'),
((SELECT id FROM areas WHERE name = 'Indirapuram' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Niti Khand 2', '201014', 'Niti Khand zone 2'),
((SELECT id FROM areas WHERE name = 'Indirapuram' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Niti Khand 3', '201014', 'Niti Khand zone 3'),
((SELECT id FROM areas WHERE name = 'Indirapuram' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Niti Khand 4', '201014', 'Niti Khand zone 4'),
((SELECT id FROM areas WHERE name = 'Indirapuram' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Shakti Khand 1', '201014', 'Shakti Khand zone 1'),
((SELECT id FROM areas WHERE name = 'Indirapuram' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Shakti Khand 2', '201014', 'Shakti Khand zone 2'),
((SELECT id FROM areas WHERE name = 'Indirapuram' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Shakti Khand 3', '201014', 'Shakti Khand zone 3'),
((SELECT id FROM areas WHERE name = 'Indirapuram' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Gyan Khand', '201014', 'Gyan Khand zone'),

-- Vaishali neighborhoods (Sectors)
((SELECT id FROM areas WHERE name = 'Vaishali' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 1', '201010', 'Vaishali Sector 1'),
((SELECT id FROM areas WHERE name = 'Vaishali' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 2', '201010', 'Vaishali Sector 2'),
((SELECT id FROM areas WHERE name = 'Vaishali' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 3', '201010', 'Vaishali Sector 3'),
((SELECT id FROM areas WHERE name = 'Vaishali' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 4', '201010', 'Vaishali Sector 4'),
((SELECT id FROM areas WHERE name = 'Vaishali' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 5', '201010', 'Vaishali Sector 5'),
((SELECT id FROM areas WHERE name = 'Vaishali' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 6', '201010', 'Vaishali Sector 6'),

-- Vasundhara neighborhoods (Sectors)
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 1', '201012', 'Vasundhara Sector 1'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 2', '201012', 'Vasundhara Sector 2'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 3', '201012', 'Vasundhara Sector 3'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 4', '201012', 'Vasundhara Sector 4'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 5', '201012', 'Vasundhara Sector 5'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 7', '201012', 'Vasundhara Sector 7'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 9', '201012', 'Vasundhara Sector 9'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 10', '201012', 'Vasundhara Sector 10'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 11', '201012', 'Vasundhara Sector 11'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 12', '201012', 'Vasundhara Sector 12'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 13', '201012', 'Vasundhara Sector 13'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 14', '201012', 'Vasundhara Sector 14'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 15', '201012', 'Vasundhara Sector 15'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 16', '201012', 'Vasundhara Sector 16'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 17', '201012', 'Vasundhara Sector 17'),
((SELECT id FROM areas WHERE name = 'Vasundhara' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Sector 18', '201012', 'Vasundhara Sector 18'),

-- Kaushambi neighborhoods
((SELECT id FROM areas WHERE name = 'Kaushambi' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'East Kaushambi', '201010', 'East Zone'),
((SELECT id FROM areas WHERE name = 'Kaushambi' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'West Kaushambi', '201010', 'West Zone'),

-- Raj Nagar neighborhoods
((SELECT id FROM areas WHERE name = 'Raj Nagar' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Raj Nagar Central', '201017', 'Central area'),
((SELECT id FROM areas WHERE name = 'Raj Nagar' AND city_id = (SELECT id FROM cities WHERE name = 'Ghaziabad')), 'Raj Nagar West', '201017', 'West area'),

ON CONFLICT DO NOTHING;

-- Add neighborhoods for Delhi areas
INSERT INTO neighborhoods (area_id, name, postal_code, description) VALUES
-- Rohini neighborhoods (Sectors)
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 1', '110085', 'Rohini Sector 1'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 2', '110085', 'Rohini Sector 2'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 3', '110085', 'Rohini Sector 3'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 4', '110085', 'Rohini Sector 4'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 5', '110085', 'Rohini Sector 5'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 6', '110085', 'Rohini Sector 6'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 7', '110085', 'Rohini Sector 7'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 8', '110085', 'Rohini Sector 8'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 9', '110085', 'Rohini Sector 9'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 10', '110085', 'Rohini Sector 10'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 11', '110085', 'Rohini Sector 11'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 13', '110085', 'Rohini Sector 13'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 14', '110085', 'Rohini Sector 14'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 15', '110085', 'Rohini Sector 15'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 16', '110085', 'Rohini Sector 16'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 17', '110085', 'Rohini Sector 17'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 18', '110085', 'Rohini Sector 18'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 19', '110085', 'Rohini Sector 19'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 20', '110085', 'Rohini Sector 20'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 21', '110085', 'Rohini Sector 21'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 22', '110085', 'Rohini Sector 22'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 23', '110085', 'Rohini Sector 23'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 24', '110085', 'Rohini Sector 24'),
((SELECT id FROM areas WHERE name = 'Rohini' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 25', '110085', 'Rohini Sector 25'),

-- Dwarka neighborhoods (Sectors)
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 1', '110075', 'Dwarka Sector 1'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 2', '110075', 'Dwarka Sector 2'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 3', '110075', 'Dwarka Sector 3'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 4', '110075', 'Dwarka Sector 4'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 5', '110075', 'Dwarka Sector 5'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 6', '110075', 'Dwarka Sector 6'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 7', '110075', 'Dwarka Sector 7'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 8', '110075', 'Dwarka Sector 8'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 9', '110075', 'Dwarka Sector 9'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 10', '110075', 'Dwarka Sector 10'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 11', '110075', 'Dwarka Sector 11'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 12', '110075', 'Dwarka Sector 12'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 13', '110075', 'Dwarka Sector 13'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 14', '110075', 'Dwarka Sector 14'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 16', '110075', 'Dwarka Sector 16'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 18', '110075', 'Dwarka Sector 18'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 19', '110075', 'Dwarka Sector 19'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 21', '110075', 'Dwarka Sector 21'),
((SELECT id FROM areas WHERE name = 'Dwarka' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Sector 23', '110075', 'Dwarka Sector 23'),

-- Other Delhi areas neighborhoods
((SELECT id FROM areas WHERE name = 'Greater Kailash' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'GK I', '110048', 'Greater Kailash I'),
((SELECT id FROM areas WHERE name = 'Greater Kailash' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'GK II', '110048', 'Greater Kailash II'),
((SELECT id FROM areas WHERE name = 'Lajpat Nagar' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'LN I', '110024', 'Lajpat Nagar I'),
((SELECT id FROM areas WHERE name = 'Lajpat Nagar' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'LN II', '110024', 'Lajpat Nagar II'),
((SELECT id FROM areas WHERE name = 'Defence Colony' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'Main', '110024', 'Defence Colony Main'),
((SELECT id FROM areas WHERE name = 'Hauz Khas' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'HK Central', '110016', 'Hauz Khas Central'),
((SELECT id FROM areas WHERE name = 'Connaught Place' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'CP Central', '110001', 'CP Central Business Area'),
((SELECT id FROM areas WHERE name = 'Karol Bagh' AND city_id = (SELECT id FROM cities WHERE name = 'Delhi')), 'KB Main', '110005', 'Karol Bagh Main Market')

ON CONFLICT DO NOTHING;
